apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eos-prod

resources:
  - ../../base

configMapGenerator:
  - name: postgres-config
    behavior: merge
    literals:
      - POSTGRES_DB=eos_prod

patches:
  - target:
      kind: StatefulSet
      name: postgres
    patch: |-
      - op: replace
        path: /spec/volumeClaimTemplates/0/spec/resources/requests/storage
        value: 20Gi
