apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: eos-prod
  namespace: argocd
  labels:
    env: prod
    tier: backend
    app.kubernetes.io/part-of: eos
spec:
  project: prod
  source:
    repoURL: "https://github.com/alvaroico/gitops-infrastructure.git"
    targetRevision: main
    path: apps/eos/overlays/prod
  destination:
    server: "https://kubernetes.default.svc"
    namespace: eos-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
