apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: eos-platform
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: gitops-repo
      sources:
        direct: true
  promotionTemplate:
    spec:
      steps:
        # 1. Clona o repositório na subpasta 'src' (evita conflito do git worktree)
        - uses: git-clone
          config:
            repoURL: "https://github.com/alvaroico/gitops-infrastructure.git"
            checkout:
              - branch: main
                path: src
        # 2. Compila os manifestos Kustomize de dev
        - uses: kustomize-build
          config:
            path: src/apps/eos/overlays/dev
            outPath: out.yaml
---
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: prod
  namespace: eos-platform
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: gitops-repo
      sources:
        stages:
          - dev # 👈 GATE: Só promove para Produção se tiver passado por Dev com sucesso
  promotionTemplate:
    spec:
      steps:
        - uses: git-clone
          config:
            repoURL: "https://github.com/alvaroico/gitops-infrastructure.git"
            checkout:
              - branch: main
                path: src
        - uses: kustomize-build
          config:
            path: src/apps/eos/overlays/prod
            outPath: out.yaml
