apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eos-prod

resources:
  - '../../base/configmap.yaml'
  - '../../base/postgres.yaml'
  - '../../base/api-deployment.yaml'
  - '../../base/api-service.yaml'
  - 'ingressroute-eos-prod.yaml'

images:
  - name: ghcr.io/alvaroico/eos
    newTag: latest
