apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: eos-dev

resources:
  - '../../base'
  - 'ingressroute-eos-dev.yaml'

images:
  - name: ghcr.io/alvaroico/eos
    newTag: dev-latest
